export const SIGNIN = 'login'
export const SIGNUP = 'register'
export const EMAIL_CONFIRM = 'confirm'
export const PASSWORD_RESET = 'reset-password'
export const SETTINGS = 'settings'
export const HOME = ''
